service: mulcho-shipping-backend

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  timeout: 30
  memorySize: 512
  environment:
    MONGO_URI: ${env:MONGODBCONNECTIONSTRING}
    CLIENT_ORIGIN: "https://www.mulcho.com.np"
    SESSION_SECRET: ${env:SESSION_SECRET}
    JWT_SECRET: ${env:JWT_SECRET}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}

functions:
  api:
    handler: src/server.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
